### ISSUE TITLE
Dataset download issue

### ISSUE THREAD

**Issue by VishalKanakamamidi** [elnino9ykl/PASS#1]
Can you please provide google drive link for the dataset with annotations for training and validation as baidu is pretty slow?

**Comment by elnino9ykl** [comment]
Hi, 

thank you.
PASS dataset google drive link is available. By the way, training was performed with Mapillary Vistas.

https://drive.google.com/file/d/1A_P2u5HUbrHZnKJYAOL2f7JLxxj69LqB/view?usp=sharing
